language: r
pandoc_version: 1.17.2
before_install:
  - tlmgr install index fontawesome
cache: packages

branches:
  only: master

script:
  - R -e rmarkdown::render"('acs-rmarkdown-cv.Rmd',output_dir='pub',output_file='cv.html')"

deploy:
  provider: pages
  local_dir: pub
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: master
  target_branch: gh-pages