language: r
pandoc_version: 1.17.2
before_install:
  - tlmgr install index fontawesome
cache: packages

branches:
  only: master

script:
  - R -e rmarkdown::render"('acs-rmarkdown-cv.Rmd',output_format='html',output_dir='www',output_file='index.html')"

deploy:
  provider: pages
  local_dir: www
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: master
  target_branch: gh-pages