---
title: "CV"
author: "Andrew Collin Stewart"
email: andrew.c.stewart@gmail.com
output:
  pdf_document:
    latex_engine: pdflatex
    template: templates/svm-latex-cv.tex
  html_document:
    df_print: paged
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
geometry: margin=1in
# jobtitle: test
keywords: R Markdown, academic CV, template
linkcolor: blue
fontawesome: yes
phone: +202 505 3633
address: San Francisco · California
updated: no
urlcolor: blue
web: andrewcstewart.com
github: andrewcstewart
bibliography: references.bib
nocite: "@*"
---

# SUMMARY

Data scientist with a strong background in applied research and development in computational biology, scientific computing, machine learning, and statistics.  Passionate about improving business processes through sound experimental design and analysis.

# TECHNICAL SKILLS

|              |                                                         |
|-------------:|---------------------------------------------------------|
| **Expertise** | Data analysis, algorithms, machine learning, statistical modeling, quality control, systems engineering, ETL, data mining, optimization, computational biology
| **Programming** | R, Python, Rust, C/C++, Java, Git, Docker , AWS |
| **Software** | RStudio, Jupyer, tidyverse, ggplot2, caret, pandas, numpy, scipy, scikit-learn, shiny, Tableau, Airflow, Spark, H2O, biopython, bioconductor, Stan
| **Machine Learning** | Classification, regression, clustering, feature engineering, validation |
| **Statistics** | Bayesian inference, hierarchical modeling, hypothesis testing, power analysis, dimensionality reduction |
| **Bioinformatics** | Sequence alignment, variant calling, expression analysis, NGS |

# PROFESSIONAL EXPERIENCE

**Twist Bioscience**, Senior Data Scientist (Bioinformatics) \hfill 2015-Present

 * Develop and deploy predictive models to optimize manufacturing processes involving gene design and assembly, DNA fragmentation screening, and clonal colony picking.  Design and analysis of experiments to improve DNA synthesis technology.  Primary architect behind data analytics platform utilizing data warehouse and ETL processes.

**Veracyte**, Scientist (R&D Data Analysis Team) \hfill 2014-2015

 * Developed high dimensional classification models for cancer diagnostics.  Provided statistical support for cross-run variability studies and power analysis for experimental designs.  Drove transition from microarray technology to next-generation sequencing based assays through development of high performance automated data analysis pipelines. 
 
**Smithsonian Institution**, Data Science Specialist (Office of the CIO) \hfill 2013-2014

 * Provided analytical support to museum and zoological research scientists in population genetics, phylogenetics, and metagenomics.  Developed genomic analyses on scientific computing clusters, including ensemble machine learning approach for classification of signatures of natural selection in genetic populations.  Coordinated efforts among researchers, information technology offices, and academic and commercial partners to develop scientific computing infrastructure.
 
**Keygene**, Bioinformatician (Applied Systems Biology) \hfill 2009-2012
 
 * Developed data pipeline for inference of gene regulatory networks using differential expression and network analysis to identify candidate genes for mutagenesis trials in crop engineering applications. Conducted exploratory data analysis and mining of hyperspectral imaging data from field crops to identify signatures of drought exposure as part of efforts to develop high throughput digital phenotyping. Constructed computational models to simulate plant architecture using Lindenmayer systems as a basis for studying optimal space utilization in greenhouse production.

**Navy Medical Research Center**, Research Assistant (Biodefense Research Directorate) \hfill 2006-2009

 * Applied sequence alignment, gene prediction, and clustering algorithms towards rapid identification of microbial pathogens from genomic sequencing data platforms. Developed high throughput data analytics system for collection, analysis, and reporting of pathogenomic data in SQL database used for multiple biodefense research applications.

# EDUCATIONAL EXPERIENCE

**Johns Hopkins University**, M.S. Computer Science \hfill 2015

**University of Maryland College Park**, B.S. Biology \hfill 2006

# TEACHING EXPERIENCE

**Johns Hopkins University**, Graduate Teaching Assistant \hfill 2016-2018

* 605.448 - Data Science
* 605.445 - Artificial Intelligence

<!-- * Spring 2018: 605.448.81 - Data Science -->
<!-- * Spring 2018: 605.445.81 - Artificial Intelligence -->
<!-- * Spring 2017: 605.448.81 - Data Science -->
<!-- * Spring 2017: 605.445.81 - Artificial Intelligence -->
<!-- * Fall 2016: 605.448.81 - Data Science -->
<!-- * Fall 2016: 605.448.82 - Data Science -->

# VOLUNTEER EXPERIENCE

**Voteocracy**, Data Science Volunteer \hfill 2016

 * Applied network analysis techniques to identify marketing targets from Twitter data.

**Bayes Impact**, Data Science Intern \hfill 2015

 * Developed multiclass predictive model of criminal activity based on geographic and census data.

# PUBLICATIONS
